apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: auto-gouggelpnv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: auto-gouggelpnv 
  name: auto-gouggelpnv
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: auto-gouggelpnv 
